### ISSUE TITLE
Does not Paste Message Back into TB from External Editor

### ISSUE THREAD

**Issue by stef204** [Frederick888/external-editor-revived#119]
After following all the instructions [here](https://github.com/Frederick888/external-editor-revived/wiki/Linux) , extension installs but, after configuration, while it opens external editor (emacs client) and let's me write a message there, it does not save or transfer (or paste) it back inside Thunderbird to be sent.  Basically, TB editor stays blank, after saving file in external editor.

I can see the message in the directory I have configured (/tmp/temp.eml) but,again, it does not paste it back into TB when exiting and saving file in emacs.  So extension not usable for me in its current form.

Can't find anything in console.

- Linux
- Thunderbird 102.10
- ExtEditorR extension version v0.60

**Comment by madhat2r** [comment]
I am having exact same issue, but on MacOS Ventura.

**Comment by stef204** [comment]
@madhat2r [this](https://github.com/muk-git/tb-my-editor) seems to be working for me.

**Comment by sschwarzer** [comment]
What are your settings in the External Editor Revived preferences in Thunderbird?

Could this probably be a situation similar to [this one](https://github.com/Frederick888/external-editor-revived/discussions/71)? I'm asking because the behavior when not using `--wait` - or a possible variant for your situation - is the same. That is, the editor opens the file, but control immediately returns to Thunderbird which only gets the original file before passing it to the editor.
