### ISSUE TITLE
Improve header processing

### ISSUE THREAD

**Issue by reagle** [Frederick888/external-editor-revived#52]
This is an enhancement request that could follow in time.

Instead of requiring one address per line, permit comma or semi-colon delimited addresses.

**Comment by Frederick888** [comment]
I actually thought about this when I wrote it, and I'd like to keep it the way it currently is.

Reasons:

1. Simplicity vs. completeness: It introduces a lot of questions, e.g. when recipients' names are included like `John Smith <jsmith@example.com>`, what happens if the person's name contains a comma? If someone has 5 recipients in one header, he'll probably want to wrap the header line, so we have to support multi-line headers as well? And if `To:` `Cc:` `Bcc:` support multi-line, what about others? It'd be nice if we can simply point people to an RFC and say, 'Look! We support everything!', but is that something that's really needed?
2. Opinionated vs. flexible: Two kinds of people use this extension. One: Wow, you can also do this, that, and those to achieve the same thing? Wonderful! Two: Ok I've already suffered through your stupidly long installation and configuration wiki, now just tell me what to do! The latter is more likely to open an issue when there's more info.
3. At the end of the day, it is extremely trivial to add a new header. So how much value it adds to this extension if I implement and document it?

**Comment by reagle** [comment]
Okay, thanks for considering the request.
